"""add dispatch tracking constraint

Revision ID: 261670b690a7
Revises: 995963e0bba6
Create Date: 2026-10-09 14:04:00.966711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261670b690a7'
down_revision: Union[str, Sequence[str], None] = '995963e0bba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_order_items', sa.Column('tracking_number', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'sales_order_items', ['tracking_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'sales_order_items', type_='unique')
    op.drop_column('sales_order_items', 'tracking_number')
    # ### end Alembic commands ###
