"""add audit logs

Revision ID: 395d01e794df
Revises: dc948adbadf5
Create Date: 2026-10-09 14:44:47.022547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '395d01e794df'
down_revision: Union[str, Sequence[str], None] = 'dc948adbadf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'entity_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('audit_logs', 'old_value',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_value',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('audit_logs', 'created_at')
    op.drop_column('audit_logs', 'created_by')
    op.drop_column('audit_logs', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.add_column('audit_logs', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.alter_column('audit_logs', 'new_value',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_value',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'entity_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
