"""add suppliers and purchase orders

Revision ID: 40317458df03
Revises: 95358fae55d5
Create Date: 2026-10-09 13:39:11.074367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '40317458df03'
down_revision: Union[str, Sequence[str], None] = '95358fae55d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'created_at')
    op.drop_column('inventory', 'updated_at')
    op.drop_column('inventory', 'created_by')
    op.drop_column('purchase_order_items', 'created_at')
    op.drop_column('purchase_order_items', 'updated_at')
    op.drop_column('purchase_order_items', 'created_by')
    op.alter_column('purchase_orders', 'po_number',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('purchase_orders', 'expected_delivery_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('purchase_orders', 'total_amount',
               existing_type=mysql.DECIMAL(precision=14, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('purchase_orders', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_column('purchase_orders', 'updated_at')
    op.drop_column('purchase_orders', 'created_by')
    op.drop_column('stock_movements', 'updated_at')
    op.drop_column('stock_movements', 'created_by')
    op.alter_column('suppliers', 'name',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('suppliers', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=True)
    op.alter_column('suppliers', 'gst_number',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('suppliers', 'address',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('email'), table_name='suppliers')
    op.create_index(op.f('ix_suppliers_email'), 'suppliers', ['email'], unique=True)
    op.create_unique_constraint(None, 'suppliers', ['gst_number'])
    op.drop_column('suppliers', 'created_at')
    op.drop_column('suppliers', 'updated_at')
    op.drop_column('suppliers', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.add_column('suppliers', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.drop_index(op.f('ix_suppliers_email'), table_name='suppliers')
    op.create_index(op.f('email'), 'suppliers', ['email'], unique=True)
    op.alter_column('suppliers', 'address',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('suppliers', 'gst_number',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('suppliers', 'phone',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('suppliers', 'name',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
    op.add_column('stock_movements', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stock_movements', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.add_column('purchase_orders', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('purchase_orders', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.alter_column('purchase_orders', 'status',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('purchase_orders', 'total_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('purchase_orders', 'expected_delivery_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('purchase_orders', 'po_number',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('purchase_order_items', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('purchase_order_items', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.add_column('purchase_order_items', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.add_column('inventory', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inventory', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.add_column('inventory', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    # ### end Alembic commands ###
