"""add customers and sales orders

Revision ID: 995963e0bba6
Revises: 40317458df03
Create Date: 2026-10-09 13:51:49.636667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '995963e0bba6'
down_revision: Union[str, Sequence[str], None] = '40317458df03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'name',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('customers', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=True)
    op.alter_column('customers', 'credit_limit',
               existing_type=mysql.DECIMAL(precision=14, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('email'), table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.drop_column('customers', 'created_at')
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'created_by')
    op.alter_column('sales_order_items', 'line_total',
               existing_type=mysql.DECIMAL(precision=14, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.drop_column('sales_order_items', 'created_at')
    op.drop_column('sales_order_items', 'updated_at')
    op.drop_column('sales_order_items', 'created_by')
    op.alter_column('sales_orders', 'so_number',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('sales_orders', 'subtotal',
               existing_type=mysql.DECIMAL(precision=14, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('sales_orders', 'tax_amount',
               existing_type=mysql.DECIMAL(precision=14, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('sales_orders', 'grand_total',
               existing_type=mysql.DECIMAL(precision=14, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('sales_orders', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('sales_orders', 'courier_name',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index(op.f('tracking_number'), table_name='sales_orders')
    op.drop_column('sales_orders', 'updated_at')
    op.drop_column('sales_orders', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_orders', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sales_orders', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.create_index(op.f('tracking_number'), 'sales_orders', ['tracking_number'], unique=True)
    op.alter_column('sales_orders', 'courier_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('sales_orders', 'status',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('sales_orders', 'grand_total',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('sales_orders', 'tax_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('sales_orders', 'subtotal',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('sales_orders', 'so_number',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('sales_order_items', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sales_order_items', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.add_column('sales_order_items', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.alter_column('sales_order_items', 'line_total',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=14, scale=2),
               existing_nullable=False)
    op.add_column('customers', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.add_column('customers', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index(op.f('email'), 'customers', ['email'], unique=True)
    op.alter_column('customers', 'credit_limit',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('customers', 'phone',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('customers', 'name',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###
