"""add returns and return items

Revision ID: dc948adbadf5
Revises: 261670b690a7
Create Date: 2026-10-09 14:23:21.275423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dc948adbadf5'
down_revision: Union[str, Sequence[str], None] = '261670b690a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_items', sa.Column('original_unit_price', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('return_items', sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.alter_column('return_items', 'condition',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_index(op.f('ix_return_items_return_id'), 'return_items', ['return_id'], unique=False)
    op.drop_constraint(op.f('return_items_ibfk_2'), 'return_items', type_='foreignkey')
    op.create_foreign_key(None, 'return_items', 'return_requests', ['return_id'], ['id'], ondelete='CASCADE')
    op.add_column('return_requests', sa.Column('so_id', sa.Integer(), nullable=False))
    op.alter_column('return_requests', 'reason',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('return_requests', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('return_requests', 'refund_amount',
               existing_type=mysql.DECIMAL(precision=14, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
    op.alter_column('return_requests', 'rejection_reason',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('return_requests', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.create_index(op.f('ix_return_requests_so_id'), 'return_requests', ['so_id'], unique=False)
    op.create_index(op.f('ix_return_requests_status'), 'return_requests', ['status'], unique=False)
    op.drop_constraint(op.f('return_requests_ibfk_1'), 'return_requests', type_='foreignkey')
    op.create_foreign_key(None, 'return_requests', 'sales_orders', ['so_id'], ['id'])
    op.drop_column('return_requests', 'created_by')
    op.drop_column('return_requests', 'sales_order_id')
    op.drop_column('return_requests', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_requests', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.add_column('return_requests', sa.Column('sales_order_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('return_requests', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'return_requests', type_='foreignkey')
    op.create_foreign_key(op.f('return_requests_ibfk_1'), 'return_requests', 'sales_orders', ['sales_order_id'], ['id'])
    op.drop_index(op.f('ix_return_requests_status'), table_name='return_requests')
    op.drop_index(op.f('ix_return_requests_so_id'), table_name='return_requests')
    op.alter_column('return_requests', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('return_requests', 'rejection_reason',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('return_requests', 'refund_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=14, scale=2),
               nullable=True)
    op.alter_column('return_requests', 'status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('return_requests', 'reason',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('return_requests', 'so_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'return_items', type_='foreignkey')
    op.create_foreign_key(op.f('return_items_ibfk_2'), 'return_items', 'return_requests', ['return_id'], ['id'])
    op.drop_index(op.f('ix_return_items_return_id'), table_name='return_items')
    op.alter_column('return_items', 'condition',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_column('return_items', 'refund_amount')
    op.drop_column('return_items', 'original_unit_price')
    # ### end Alembic commands ###
